### ISSUE TITLE
Tree_Javascript or Tree_JavaScript?

### ISSUE THREAD

**Issue by SlowFox71** [wikimedia/less.php#103]
I included lessphp to one of my projects and my automatic syntax checker complained about lib/Less/Tree/JavaScript.php not to exist.

Taking a closer look there is Less_Tree_Javascript used in the class itself and in Parser.php, but Less_Tree_JavaScript in Functions.php and Tree/Quoted.php.

Not a big issue, but either of these should be corrected.

**Comment by Krinkle** [comment]
@SlowFox71 Good catch! Classes are case-insensitive in PHP but these should be consistently cased indeed.

Would you be interested in submitting a patch for this?

You can submit one via https://gerrit-patch-uploader.toolforge.org/ using only a `git diff` and your Wikipedia.org or mediawiki.org account.

**Comment by SlowFox71** [comment]
Yes, I can submit a patch - just tell me which notation is the preferred one.

(I started checking this because I sometimes use class names for array key like $name[\MyClass::clas] = 'My class', and then case sensitivity is important)

**Comment by Krinkle** [comment]
I'd say the preferred form is `Less_Tree_JavaScript`. We aim to match upstream whenever possible:

https://github.com/less/less.js/blob/v4.1.3/dist/less.js#L7196
https://github.com/less/less.js/blob/v4.1.3/dist/less.js#L3863

**Comment by SlowFox71** [comment]
Ok, done - hopefully everything is fine.

You might consider renaming the file into JavaScript.php as well; git diff does not reflect this.

**Comment by Krinkle** [comment]
https://gerrit.wikimedia.org/r/c/mediawiki/libs/less.php/+/975430

**Comment by Krinkle** [comment]
Released in v4.2.0, https://github.com/wikimedia/less.php/blob/v4.2.0/CHANGES.md
