### ISSUE TITLE
Parser Exception parsing "filter: alpha(opacity=0);"

### ISSUE THREAD

**Issue by ThomasKWD** [wikimedia/less.php#112]
Hi,

first please tell me when already an opened issue for this. Could not find one here.

Switching from 4.1.0 to 5.0.0 i found that the Parser.php could not handle the CSS line "filter: alpha(opacity=0);" anymore.

I could easily fix it in code (at least for my use case) because there simply must be a distinguish between "0" and ! (=not, falsy including '0').  Hence it only breaks on opacity value 0.

![Bildschirmfoto 2024-08-01 um 10 17 32](https://github.com/user-attachments/assets/b0fe183b-dd2f-4331-8492-ae75fe0f425f)

Kind regards
Thomas

**Comment by Krinkle** [comment]
Fixed in https://github.com/wikimedia/less.php/commit/0d8073016bf214439d566fbf306e526780da11e9. It'll go out in a minor release shortly.

Thanks again for reporting this, @ThomasKWD!
