### ISSUE TITLE
Variables in @import statements cause "variable not found" Less_Exception_Compiler

### ISSUE THREAD

**Issue by DemianX0** [wikimedia/less.php#32]
```
@theme: 'custom';
@import '@{theme}.less';
```
Results in:
```
Less_Exception_Compiler from line 49 of vendor\wikimedia\less.php\lib\Less\Tree\Variable.php:
 variable @theme is undefined in variables.less on line 2, column 9
```

Reported upstream:  https://github.com/oyejorge/less.php/issues/352
Fixed by (2 patches):  https://github.com/oyejorge/less.php/issues/352#issuecomment-331259863
https://github.com/kylekatarnls/less.php/commit/e3d4aa4b5695000fa527b152656742a87afde9b1
https://github.com/kylekatarnls/less.php/commit/637fd9346cd72d4e277de9a263820d98867ec597

**Comment by cmoeke** [comment]
Any updates? What is needed to merge #33, can i help here?

I would like to use less.php to compile [Fomantic-UI theme.less](https://github.com/fomantic/Fomantic-UI/blob/develop/src/theme.less) which needs this feature.
