### ISSUE TITLE
Is 2.0 still supported?

### ISSUE THREAD

**Issue by NateWr** [wikimedia/less.php#42]
We're currently using a 1.x version in our open source application and would like to update. However, the PHP version dependency in v3.0 is too high for our community. We are considering using v2.0 but I noticed that it was released in February and v3.0 was released just a month later. Since then no updates have been provided for v2.0.

Is v2.0 a safe version to go with? Is there anything we should be aware of in terms of long-term maintenance?

Thanks!

**Comment by jdforrester** [comment]
The 2.0 release exists purely for the support for (dead, end-of-life'ed, not security-supported) versions of PHP, yes.

I didn't expect that we'd backport bugfixes to it, but if there's a major issue/bug we could do that.

**Comment by NateWr** [comment]
Thanks for the quick reply @jdforrester!
