### ISSUE TITLE
Embrace our fork

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/less.php#43]
Upstream has archived their repo and points to ours as the recommmended path forward (<https://github.com/oyejorge/less.php>).

Let's therefore set our repo  up properly:

* [x] Update or remove descriptions and websites references in code, documentation and other meta data that refer to upstream since those are now stale.
* [x] Convert the repo to use follow Wikimedia's boilerplate for libraries.
  * [x] Latest PHPCS Codesniffer as used by MW.
  * [x] Latest PHPUnit.
  * [x] Add Phan and make pass.
* [x] Set up a mirror in Gerrit or move the repo to Gerrit so as to not be dependent on GitHub for our production source code.
* [x] Set up a Doxygen pipeline in WMF CI (or somehow with Travis commiting to a gh-pages branch, to a subdirectory based on the release tag and branch), and ensure all useful information from the upstream website is preserved in a set of `docs/` Markdown pages rendered on the site.

See <https://www.mediawiki.org/wiki/Manual:Developing_libraries>.

**Comment by moseleyi** [comment]
It would be very beneficial to compile a list of CSS rules that will need converting. I've been using the original repo for quite a while but the lack of support for newer features almost made me to switch to JS-based but I hung on tight as I prefer PHP.

**Comment by Krinkle** [comment]
Ticked off Codesniffer, per https://github.com/wikimedia/less.php/pull/53.

**Comment by DannyS712** [comment]
+1 to `move the repo to Gerrit`

**Comment by Krinkle** [comment]
Ticked off docs, descriptions and website per https://github.com/wikimedia/less.php/pull/58.

**Comment by Krinkle** [comment]
Phan build added, but not yet passing (various warnings, build status ignored), ref https://github.com/wikimedia/less.php/commit/dc217065e4530a04f1a475d96dee500f41add1df.

**Comment by DannyS712** [comment]
Is there anything I can do to help move this to gerrit? The interface there is a lot easier imo

**Comment by Krinkle** [comment]
* PHPCS and Phan are set up, passing, and enforced via CI.
* Repo has been moved to Wikmedia Gerrit.
* Enabled mirror back to GitHub (re-using the existing repo here, and thus preserving references to old issues/discussions that may be referenced in commit messages etc.).
* Test coverage up at <https://doc.wikimedia.org/cover/mediawiki-libs-less.php/> (as per <https://gerrit.wikimedia.org/r/c/integration/config/+/879687>).
* Doxygen output up at <https://doc.wikimedia.org/mediawiki-libs-less.php/> (as per <https://gerrit.wikimedia.org/r/879879>).
