### ISSUE TITLE
Update compatibility to support Less.js 3.13.1

### ISSUE THREAD

**Issue by mrtuvn** [wikimedia/less.php#55]
Should we need update less from 2.5.3 to more recently version ? Example 3.13.1

https://github.com/wikimedia/less.php/blob/a486d78b9bd16b72f237fc6093aa56d69ce8bd13/lib/Less/Version.php#L12

Current we stay at long time in 2.5.3 version
Should we have update to 3.9.0 or 3.13.1 ? Is there any timeline or eta for that ?

**Comment by jdforrester** [comment]
Yeah, we should probably do this. I don't know how much work this would be, however.

**Comment by mrtuvn** [comment]
HI any plan for update compatible to less 4.1.1 ?
Thanks

**Comment by Krinkle** [comment]
@mrtuvn I don't think our maintenance budget for Less.php will be able to accomodate the additional cost for developing that. However, I think I can make time to review/test/release pull requests that incrementally make the relevant improvements for Less 4 compat.

**Comment by mrtuvn** [comment]
i think you can open sponsors button for this repo. Just my opinions

**Comment by Krinkle** [comment]
@mrtuvn Maintainers like myself are working part-time or full-time for Wikimedia Foundation. Additional funds would not help us in terms of priorisation. This is likely something we can't prioritise within the foundation scope unless Wikipedia needs it (e.g. MediaWiki core).

**Comment by Krinkle** [comment]
Equivalent task on our own issue tracker: https://phabricator.wikimedia.org/T288498.

This is now in progress!

**Comment by Krinkle** [comment]
Closing in favour of specific tasks elsewhere in the issue tracker. The 5.0.0 release is out and has changed our target from 2.5 to 3.13, with various new features, and more to come.
