### ISSUE TITLE
Parent selector "&" symbol not treated when in a :not() pseudo-class

### ISSUE THREAD

**Issue by Lythness** [wikimedia/less.php#56]
Hi,
current selector in pseudo class selector :not() isn't treated : 
```
.foo { 
    width: 100px;

    &-bar {
        background: blue;
    }
            
    &:not(&-bar) {
        background: green;
    }
}
```

Outputs :

```
.foo {
    width: 100px;
}
.foo-bar {
    background: blue;
}
.foo:not(&-bar) {
    background: green;
}
```
But it must be returned :
```
.foo {
    width: 100px;
}
.foo-bar {
    background: blue;
}
.foo:not(.foo-bar) {
    background: green;
}
```

**Comment by edg2s** [comment]
Also reported downstream: https://phabricator.wikimedia.org/T204816

**Comment by Krinkle** [comment]
From https://phabricator.wikimedia.org/T204816:
> cab5103233b8340de5319ab545851afdffabfe43 Less_Ruleset: Fix support for nested parent selectors
>
> Reviewed-on: https://gerrit.wikimedia.org/r/882188
