### ISSUE TITLE
Improve "Operation on an invalid type" error with source line

### ISSUE THREAD

**Issue by timint** [wikimedia/less.php#84]
This library needs to provide a little more feedback on this fatal compilation error: "Operation on an invalid type."
I'm thinking what .less file and which line.

The .less files I have, they compile nicely with [less-plugin-clean-css](https://www.npmjs.com/package/less-plugin-clean-css) for Node.js. But give this error with less.php.

To determine why it does not compile with less.php we need at least a hint.

Reference:
https://github.com/wikimedia/less.php/search?q=Operation+on+an+invalid+type

**Comment by timint** [comment]
I managed to replace this line:
https://github.com/wikimedia/less.php/blob/480d7d87cd65974777c347767825eb60f3226189/lib/Less/Tree/Operation.php#L44

With this:
`				throw new Less_Exception_Compiler( "Operation on an invalid type ". $a->name ."(". implode(', ', array_column($a->args, 'value')) .") in ". $a->currentFileInfo['currentUri'] );`

And figured out this library does not support CSS variables as is `var(--variable-name)`. Which is another topic.

**Comment by Krinkle** [comment]
Imported to our primary issue tracker at <https://phabricator.wikimedia.org/T344197>.

**Comment by Krinkle** [comment]
Fixed in https://gerrit.wikimedia.org/r/c/mediawiki/libs/less.php/+/976671/.

**Comment by Krinkle** [comment]
Released in v4.2.0, https://github.com/wikimedia/less.php/blob/v4.2.0/CHANGES.md
