### ISSUE TITLE
PHP v5.6-7.0 deprecation

### ISSUE THREAD

**Issue by dleffler** [wikimedia/less.php#89]
Might want to note in the changes that less.php v3.2.0 is no longer compatible with PHP v5.6 nor v7.0. This is due to use of ?? as Null coalescing operator, and visibility options for const properties.

**Comment by Krinkle** [comment]
Hi @dleffler,

We document breaking changes as part of our release notes in [CHANGES.md](https://github.com/wikimedia/less.php/blob/main/CHANGES.md), and (if you use Composer) these are also advertised/enforced via `requires` in `composer.json`.

* less.php v1.8.1 was the last version to support PHP 5.6 or PHP 7.0.
* less.php v2.0.0 required PHP 7.1+.
* less.php v3.0.0 requires PHP 7.2+.

v3.2.0 does not raise this requirement, though it indeed gradually increased use of PHP 7.2-specific syntax. I'm sorry if you previously happen to not run into this yet, but I hope the above helps to understand that this was already required.
