### ISSUE TITLE
@container queries support?

### ISSUE THREAD

**Issue by melcak** [wikimedia/less.php#97]
Hello, would be possilbe to add support for @container queries like:

`@container (max-width: 650px) { ... }`

Right now it throws: **Fatal error: Uncaught Less_Exception_Chunk: ParseError: Unexpected input**

**Comment by Gappa** [comment]
Discussed/explained here: https://github.com/wikimedia/less.php/issues/91#issuecomment-1440260767

**Comment by Krinkle** [comment]
Duplicate of https://github.com/wikimedia/less.php/issues/91.
